name: Stock Scanner (Telegram)

on:
  workflow_dispatch:
    inputs:
      RUN_AFTER_HOURS:
        type: boolean
        description: "Allow running outside US market hours?"
        default: false
      ALWAYS_NOTIFY:
        type: boolean
        description: "Send a summary even if there are no NEW alerts?"
        default: false
      PING_ON_START:
        type: boolean
        description: "Send a startup ping?"
        default: false
      PING_ON_END:
        type: boolean
        description: "Send a completion ping?"
        default: false
      TICKERS:
        description: "Optional override list (comma/space separated)"
        required: false
        default: ""
  # Every 30 minutes on weekdays (UTC). Step below filters to US RTH by default.
  schedule:
    - cron: "*/30 * * * 1-5"

concurrency:
  group: stock-scanner
  cancel-in-progress: false

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      TZ: America/New_York
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy yfinance requests certifi
          fi

      # Default: skip runs outside US RTH unless user allows after-hours
      - name: Skip outside US RTH (unless overridden)
        run: |
          if [ "${{ inputs.RUN_AFTER_HOURS }}" != "true" ]; then
            now=$(TZ=America/New_York date +%H%M)
            dow=$(TZ=America/New_York date +%u)
            if [ "$dow" -ge 6 ] || [ "$now" -lt 0930 ] || [ "$now" -gt 1600 ]; then
              echo "Outside US RTH — exiting."
              exit 0
            fi
          fi

      - name: Run scanner
        env:
          # --- Telegram secrets (set in repo Settings → Secrets and variables → Actions) ---
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # Use one of these:
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}   # single chat id
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}  # OR multiple: "-480...,11122..." or "-480... 11122..."

          # --- Behavior toggles passed to the script ---
          MARKET_ONLY: ${{ inputs.RUN_AFTER_HOURS && 'false' || 'true' }}
          ALWAYS_NOTIFY: ${{ inputs.ALWAYS_NOTIFY && 'true' || 'false' }}
          TELEGRAM_PING_ON_START: ${{ inputs.PING_ON_START && 'true' || 'false' }}
          TELEGRAM_PING_ON_END:   ${{ inputs.PING_ON_END && 'true' || 'false' }}
          TICKERS: ${{ inputs.TICKERS }}
        run: |
          python scanner_dual_tf_vp_spyder_telegram_loop_dip3.py

      - name: Upload CSV + state as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scanner-output
          path: |
            scanner_dual_tf_vp.csv
            alerts_seen.json
